FROM ubuntu:12.04
RUN DEBIAN_FRONTEND=noninteractive apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y \
    ruby1.9.3 build-essential libc6-dev libffi-dev \
    libgdbm-dev libncurses5-dev libreadline-dev libssl-dev \
    libyaml-dev zlib1g-dev
RUN gem install fpm --bindir=/usr/bin --no-rdoc --no-ri
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y curl


RUN curl ftp://ftp.ruby-lang.org/pub/ruby/<%= base_ver %>/ruby-<%= version %>.tar.gz|tar oxzC /tmp
WORKDIR /tmp/ruby-<%= version %>

RUN ./configure --disable-install-doc --prefix=/usr
RUN make install DESTDIR=/tmp/fpm
WORKDIR /tmp

RUN fpm \
    -s dir \
    -t deb \
    -n ruby \
    -v <%= version %>-1 \
    -d libc6-dev \
    -d libffi-dev \
    -d libgdbm-dev \
    -d libncurses5-dev \
    -d libreadline-dev \
    -d libssl-dev \
    -d libyaml-dev \
    -d zlib1g-dev \
    -C /tmp/fpm \
    -p ./ruby-<%= version %>.deb \
    usr
