FROM ubuntu:14.04
MAINTAINER Steve Oberther stephenoberther@gmail.com

ENV REFRESHED_AT 2015-07-15
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get -y update
RUN apt-get install -y python-yaml python-jinja2 python-apt python-pycurl git wget software-properties-common
