FROM ubuntu:14.04
MAINTAINER Steve Oberther stephenoberther@gmail.com
ENV REFRESHED_AT 2014-09-20

RUN DEBIAN_FRONTEND=noninteractive apt-get -y update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y python-yaml python-jinja2 python-apt python-pycurl git wget software-properties-common
