FROM ubuntu:saucy
MAINTAINER Steve Oberther stephenoberther@gmail.com


RUN DEBIAN_FRONTEND=noninteractive apt-get -y update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y python-yaml python-jinja2 python-apt python-pycurl git wget software-properties-common
