version: '2'

services:
  consul-1:
    image: smo921/consul:latest
    container_name: consul-1
    hostname: consul-1
    networks:
      backend:
    environment:
      - CONSUL_CLUSTER_SIZE=1
  vault:
    image: smo921/vault
    container_name: vault
    hostname: vault
    networks:
      backend:
    cap_add:
      - IPC_LOCK
    depends_on:
      - consul-1
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200/
  zookeeper:
    image: smo921/zookeeper
    container_name: zookeeper
    hostname: zookeeper
    networks:
      backend:
  kafka:
    image: smo921/kafka
    container_name: kafka
    hostname: kafka
    networks:
      backend:
    depends_on:
      - zookeeper
  elastic:
    image: smo921/elastic:2.3.1
    container_name: elastic
    hostname: elastic
    networks:
      backend:
  kibana:
    image: smo921/kibana:4.5.0
    container_name: kibana
    hostname: kibana
    networks:
      backend:
    ports:
      - 5601:5601
    depends_on:
      - elastic

networks:
  backend:
    driver: bridge
