- hosts: all
  remote_user: vagrant
  sudo: yes
  tasks:
    - name: Make /home/rbenv/.ssh
      command: mkdir /home/rbenv/.ssh creates=/home/rbenv/.ssh
    - name: Install github ssh key
      shell: ssh-keyscan github.com >> /home/rbenv/.ssh/known_hosts
- hosts: all
  remote_user: vagrant
  sudo: yes
  vars:
    rbenv_ruby_versions:
      - 2.1.2
      - 1.9.3-p484
    rbenv_ruby_default: 2.1.2
  roles:
    - mivok0.users
    - angstwad.docker_ubuntu
    - Lytol.rbenv
  tasks:
    - meta: flush_handlers
    - name: Install python-pip
      apt: name=python-pip state=present
    - name: Install docker-py
      pip: name=docker-py
    - name: build docker base
      docker_image: path="/docker_images/base" name="smo921/base"
    - name: fetch docker images
      shell: ls /docker_images/ | grep -v base
      register: image_list
    - name: build docker images
      docker_image: path="/docker_images/{{ item }}" name="smo921/{{ item }}"
      with_items: image_list.stdout_lines
