FROM smo921/base
MAINTAINER Steve Oberther stephenoberther@gmail.com

ENV REFRESHED_AT 2015-01-04
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update
RUN apt-get -y install python-dev librsync-dev python-pip
